// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBymWi6tyE55myloq4sBLTOno-f8KvRfCw',
    appId: '1:132826475569:web:e0deea06203b9e4018f910',
    messagingSenderId: '132826475569',
    projectId: 'chatty-app-b062f',
    authDomain: 'chatty-app-b062f.firebaseapp.com',
    storageBucket: 'chatty-app-b062f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJhp3oeV4Xue1Lmng184ycfn63mPgFT_k',
    appId: '1:132826475569:android:1e4ace68c442543618f910',
    messagingSenderId: '132826475569',
    projectId: 'chatty-app-b062f',
    storageBucket: 'chatty-app-b062f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMuFlr2WiBN-bUvQTPjXe7GcWnU5sj30',
    appId: '1:132826475569:ios:19b823669336268718f910',
    messagingSenderId: '132826475569',
    projectId: 'chatty-app-b062f',
    storageBucket: 'chatty-app-b062f.appspot.com',
    iosClientId:
        '132826475569-4ljcr9fqmdrbhdot49t8o2fnt920f541.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
